services:
  postgres:
    image: postgres:16-alpine
    container_name: iba-postgres
    environment:
      POSTGRES_DB: iba_db
      POSTGRES_USER: iba_user
      POSTGRES_PASSWORD: iba_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - iba-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: iba-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@iba.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - iba-network

volumes:
  postgres_data:

networks:
  iba-network:
    driver: bridge

